stages:
  preprocess:
    cmd: python src/data_prep.py
    deps:
    - data/raw/telco_churn.csv
    - src/data_prep.py
    outs:
    - data/processed/telco_churn_clean.csv
  train_rf:
    cmd: python src/train_rf.py
    deps:
    - data/processed/telco_churn_clean.csv
    - params.yaml
    - src/train_rf.py
    outs:
    - models/model_rf.pkl
    metrics:
    - metrics_rf.json:
        cache: false
